### PR TITLE
Report the correct repo URL even if GitHub lies

### PR DESCRIPTION
**Pull request by fregante**
Fixes https://github.com/fregante/github-url-detection/issues/53
Fixes https://github.com/sindresorhus/refined-github/issues/3743

### CODE REVIEW

**Comment by yakov116** [comment]
I'll test it in the morning. It's crazy that they are inconsistent with everything lately!

**Comment by fregante** [comment]
GitHub entered the _move fast break things_ phase

**Comment by yakov116** [comment]
I am trying to find the place you said "when github switches to react this extension (RGH) is a goner"

**Comment by yakov116** [comment]
Found it! https://github.com/sindresorhus/refined-github/pull/1159

**Comment by fregante** [comment]
That hasn't happened yet, but they've been switching to utility classes, which is almost as bad.

**Review by yakov116 — APPROVED** [review]

**Pull request merged**
