### PR TITLE
Add `isNewRepoTemplate`

### LINKED ISSUE #69: Template generation page should not be part of `isRepo`
Test URL https://github.com/fregante/browser-extension-template/generate

### PR DESCRIPTION
**Pull request by yakov116**
Fixes #69

### CODE REVIEW

**Comment by yakov116** [comment]
@fregante any idea why its timing out?

**Review by fregante — APPROVED** [review]

**Comment by fregante** [comment]
Can you move the ava timeout configuration from the npm script to the “ava” section in package.json? GHA calls AVA directly, not the script

**Comment by yakov116** [comment]
🤷

**Comment by fregante** [comment]
It’s recursively calling. Itself. You can’t use getRepo inside isRepo

**Comment by yakov116** [comment]
> It’s recursively calling itself. You can’t use getRepo inside isRepo

duh!!

**Comment by fregante** [comment]
There’s another of those checks inside isRepo with the same problem. Check how it was solved. I think isRepoSearch

**Comment by fregante** [comment]
It’s annoying that the test error was useless until you increased the timeout considerably and the “max stack” error was visible.

**Comment by fregante** [comment]
LGTM

**Pull request merged**
