### PR TITLE
Add live demo

### PR DESCRIPTION
**Pull request by fregante**
- [x] Auto-deploy to GitHub pages

### CODE REVIEW

**Comment by fregante** [comment]
@yakov116 @notlmn enjoy: https://fregante.github.io/github-url-detection/

**Comment by yakov116** [comment]
Awesome!

**Comment by notlmn** [comment]
Perfect @fregante, and thanks for the invite 🎉

**Comment by yakov116** [comment]
I played around with it, amazed how fast it is. Great Job!

**Pull request merged**
