### PR TITLE
Add `isPRFile404`

### PR DESCRIPTION
**Pull request by yakov116**
Does not follow https://github.com/sindresorhus/refined-github/pull/3314#discussion_r449908749 😄 

`isPRCommit404` exists. I need the file 404

### CODE REVIEW

**Comment by yakov116** [comment]
test is timing out...

**Comment by fregante** [comment]
I don't know what's wrong with the tests, they're throwing here too: https://github.com/fregante/github-url-detection/pull/21

**Comment by fregante** [comment]
Try writing the tests again, copy the existing one and make small changes until it works/break. That's how I fixed https://github.com/fregante/github-url-detection/pull/21

**Comment by yakov116** [comment]
Weird...
Ok will try

**Comment by yakov116** [comment]
@fregante passed...

**Comment by yakov116** [comment]
🚀 ?

**Pull request merged**
