### PR TITLE
Fix relative URLs in getRepoURL

### LINKED ISSUE #28: `[property="og:url"]` does not give the full url on the release page
=> `"/sindresorhus/refined-github/releases"`

https://github.com/sindresorhus/refined-github/releases

### PR DESCRIPTION
**Pull request by fregante**
This should fix #28

### CODE REVIEW

**Comment by fregante** [comment]
cc @yakov116

**Comment by yakov116** [comment]
Works!

**Comment by fregante** [comment]
This means I have to release a hotfix for RG, doesn't it?

**Comment by yakov116** [comment]
Yes

**Comment by fregante** [comment]
Did it only break `releases-tab` and `recently-pushed-branches-enhancements` on Releases? Doesn't feel too urgent so far. Let's see if we broke anything else first (or wait until Thursday)

**Comment by yakov116** [comment]
As soon as I saw it broke on releases I did a mass check. I dont see any where else.

**Comment by fregante** [comment]
Thank you!

**Pull request merged**
