### PR TITLE
Add `isDiscussionList` and `isDiscussion`

### PR DESCRIPTION
**Pull request by yakov116**
Tested

### CODE REVIEW

**Comment by fregante** [comment]
How similar is the DOM? Because hasComments let’s you assume we have certain classes and elements, and loading mechanism. It’s worth taking a look at what features use that detection and if they cause errors on Discussions if hasComments includes that.

**Comment by yakov116** [comment]
> How similar is the DOM? Because hasComments lets you assume we have certain classes and elements, and loading mechanism. It’s worth taking a look at what features use that detection and if they cause errors on Discussions if hasComments includes that.

> Untested

Testing now

**Comment by fregante** [comment]
Not compatible?

**Review by fregante — APPROVED** [review]

**Comment by fregante** [comment]
You can merge and publish as `minor` when it's ready

 
Screen Shot

**Comment by yakov116** [comment]
> Not compatible?

Not at all!, I got about 12 errors LOL

**Comment by fregante** [comment]
Thanks for the PR and especially for the sponsorship, you shouldn't have! 😁

**Comment by yakov116** [comment]
Na, you deserve it. I have gained from your work immensely!

**Pull request merged**
